# Use an official Python runtime as a parent image
FROM python:3.10-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app/install/
# Assuming requirements.txt is located at install/requirements.txt in your host machine
COPY install/requirements.txt /app/install/requirements.txt

RUN pip install --upgrade pip

# Install any needed packages specified in requirements.txt
RUN pip install --require-hashes --no-cache-dir -r /app/install/requirements.txt

# Copy the entire application code into the container at /app
# Assuming your Flask app file is named app.py and is in the root of your project
COPY app_predict.py /app

# Expose the port that the Flask app will run on
EXPOSE 8081

# Define environment variable for Flask
ENV FLASK_APP=app_predict.py

# Run the Flask application when the container starts
# Using '0.0.0.0' as host to make it accessible from outside the container
CMD ["flask", "run", "--host=0.0.0.0", "--port=8081"]